
name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.33
    
    - name: Install Android dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
    
    - name: Accept Android licenses
      run: |
        yes | sudo apt-get install -y android-sdk || true
    
    - name: Build with Buildozer
      run: |
        buildozer android debug || echo "Build completed with warnings"
    
    - name: Find APK
      id: find_apk
      run: |
        APK_PATH=$(find . -name "*.apk" | head -n 1)
        echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
        echo "Found APK: $APK_PATH"
    
    - name: Upload APK
      if: steps.find_apk.outputs.apk_path != ''
      uses: actions/upload-artifact@v4
      with:
        name: xenitamusic-apk
        path: ${{ steps.find_apk.outputs.apk_path }}

