
name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Accept Android Licenses & Install Build Tools
      run: |
        yes | sdkmanager --licenses || true
        yes | sdkmanager --update
        yes | sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
        export ANDROID_HOME=$HOME/.android
        export PATH=$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
    
    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip git openjdk-17-jdk
        pip install --upgrade pip
        pip install buildozer cython==0.29.33
    
    - name: Initialize Buildozer (if not exists)
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
    
    - name: Build APK with Buildozer
      run: |
        buildozer android debug
    
    - name: Find APK
      id: find_apk
      run: |
        APK_PATH=$(find . -type f -name "*.apk" | head -n 1)
        if [ -z "$APK_PATH" ]; then
          echo "No APK found!"
          exit 1
        fi
        echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
        echo "Found APK: $APK_PATH"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: toohuman2025-apk
        path: ${{ steps.find_apk.outputs.apk_path }}
