
name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk wget \
          libffi-dev libssl-dev python3-pip \
          build-essential libltdl-dev \
          ccache autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev \
          libtinfo5 cmake libffi-dev
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.33
        pip install https://github.com/kivy/python-for-android/archive/develop.zip
    
    - name: Setup Android environment
      run: |
        echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
    
    - name: Cache Buildozer
      uses: actions/cache@v3
      with:
        path: |
          ~/.buildozer
        key: buildozer-${{ hashFiles('buildozer.spec') }}
    
    - name: Build APK
      run: |
        yes | buildozer android debug
    
    - name: List files
      if: always()
      run: |
        ls -la
        ls -la bin/ || echo "No bin directory"
    
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: xenitamusic-apk
        path: bin/*.apk
    
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: .buildozer/android/platform/build-*/build/outputs/logs/
